### ISSUE TITLE
Slack command fails with ` "dispatch_unknown_error"`

### ISSUE THREAD

**Issue by Genysys** [jitsi/jitsi-slack#12]
**Operating System**: Ubuntu 18.04
**Go version**: 1.11

Description:

I have deployed the code to a server and run the following command:

```
go run cmd/api/main.go
{"level":"info","time":"2020-05-10T15:27:01Z","message":"listening on :8080"}
```

I have also created a TokenTable and ServerCfg table in AWS and supplied the credentials as 

Unfortunately,  when I try a slash command to run Jitsi, I get the following error:

```
/jitsi failed with the error "dispatch_unknown_error"
```

I will appreciate any guidance on this.

**Comment by sawall** [comment]
I've added some info to the README.md in the repo that will hopefully be helpful when configuring your server.

Note that a new release has just been issued that supports Slack's current OAUTH 2.0 model.
