### ISSUE TITLE
Looking for a possibilty to configure a self hosted Jitsi Server 

### ISSUE THREAD

**Issue by Procuria** [jitsi/jitsi-slack#13]
Hello,

is there a possibilty to configure a self hosted Jitsi-Instance as standard for the jitsi-Bot ?

I cant find anything in the documentation about this and would be very happy if you could point me the direction.

many thanks in advance

**Comment by damencho** [comment]
After installing the already existing integration in Slack it defaults to meet.jit.si, but you can change that using host command. Info about that is available in the integration help inside Slack, use command help.

**Comment by damencho** [comment]
![Screenshot_20200515-073357~2](https://user-images.githubusercontent.com/3263098/82051024-c1d18180-967e-11ea-8106-9fb7d4342f44.png)
