### ISSUE TITLE
Jisti App does not seem to generate conferences but just links to jit.si website.

### ISSUE THREAD

**Issue by ptrxyz** [jitsi/jitsi-slack#26]
According to this:
![image](https://user-images.githubusercontent.com/209056/161527558-360e9429-873f-4d18-aa57-832cc3b2e863.png)
(from here https://jitsi.org/slack/)

The app should generate a custom conference link yet it just brings me to the normal Jitsi website. Is there anything I do wrong? I took the app as is from the Slack App directory as I am fine with using the public Jitsi servers.

![image](https://user-images.githubusercontent.com/209056/161527943-998e4fab-026d-444a-b091-94edeafc0d4c.png)

**Comment by saghul** [comment]
Did you click the Join button? we no longer display the full link, but the join button does go to the right place.

**Comment by damencho** [comment]
There is a host command to configure the host to use. Using meet.jit.si os also fine.

**Comment by ptrxyz** [comment]
oh, this is what i was looking for. Thanks a bunch!
